### PR TITLE
Start of Python 3 Support

### PR DESCRIPTION
**Pull request by streeter**
Still got a few more things to do. Better support depends on at least the following PRs:

- https://github.com/GoogleCloudPlatform/appengine-gcs-client/pull/33
- https://github.com/jeremydw/protorpc-standalone/pull/1
- https://github.com/GoogleCloudPlatform/webapp2/pull/110

### CODE REVIEW

**Comment by jeremydw** [comment]
Thanks for this -- looks good so far. Will you be pushing more commits here or is this ready to go?

Separately -- can you please update the PR to merge into `develop` instead of `master`? Our current workflow has a long-running `develop` branch with `master` mirroring the release. I'm thinking about changing this and just using tags instead, but that's how it is right now. LMK if you have any thoughts on that.

**Comment by streeter** [comment]
> Will you be pushing more commits here or is this ready to go?

I'd like to continue more Py3 support, but kept running into package compatibilities. Mostly around all the GAE stuff. So your call if you want one giant PR with all the Py3 stuff in it, or ok with smaller PRs to incrementally bring support up.

> Separately -- can you please update the PR to merge into develop instead of master? Our current workflow has a long-running develop branch with master mirroring the release. I'm thinking about changing this and just using tags instead, but that's how it is right now. LMK if you have any thoughts on that.

Most projects have one `master` branch, that PRs merge into, and then you just tag the release. It isn't that often that I've seen you need to a hotfix that you can't release whatever is on `master`. GitHub [wrote](https://guides.github.com/introduction/flow/) about this kind of flow.

I'll create a new PR to merge into develop (GitHub [doesn't have a way to change the branch for a PR after the fact](https://github.com/isaacs/github/issues/18)). You might also consider creating a [`CONTRIBUTING.md`](https://help.github.com/articles/setting-guidelines-for-repository-contributors/) file to let contributors know to base the branch on `develop`, if you go that route.

**Comment by jeremydw** [comment]
OK, this all sounds good. I think we should adopt that approach. One master
branch with tags for releases. And master should only contain work that's
ready for release -- we can have long-running feature branches. We'll also
add a short CONTRIBUTING.md to describe the workflow. Thanks @streeter.

On Tue, May 3, 2016 at 5:41 PM, Chris Streeter <notifications@github.com>
wrote:

> Will you be pushing more commits here or is this ready to go?
>
> I'd like to continue more Py3 support, but kept running into package
> compatibilities. Mostly around all the GAE stuff. So your call if you want
> one giant PR with all the Py3 stuff in it, or ok with smaller PRs to
> incrementally bring support up.
>
> Separately -- can you please update the PR to merge into develop instead
> of master? Our current workflow has a long-running develop branch with
> master mirroring the release. I'm thinking about changing this and just
> using tags instead, but that's how it is right now. LMK if you have any
> thoughts on that.
>
> Most projects have one master branch, that PRs merge into, and then you
> just tag the release. It isn't that often that I've seen you need to a
> hotfix that you can't release whatever is on master. GitHub wrote
> <https://guides.github.com/introduction/flow/> about this kind of flow.
>
> I'll create a new PR to merge into develop (GitHub doesn't have a way to
> change the branch for a PR after the fact
> <https://github.com/isaacs/github/issues/18>). You might also consider
> creating a CONTRIBUTING.md
> <https://help.github.com/articles/setting-guidelines-for-repository-contributors/>
> file to let contributors know to base the branch on develop, if you go
> that route.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/grow/grow/pull/207#issuecomment-216710667>
>



-- 
jeremydw

**Comment by jeremydw** [comment]
Happy to merge this in incrementally. Especially because this updates `boto` which I think will resolve another issue we encountered.

**Pull request merged**
