### PR TITLE
Adding translator comments to the spreadsheet.

### PR DESCRIPTION
**Pull request by Zoramite**
Adds a protected column for any translator comments to be shown by the translation in the 3rd column.

Part of #419

### CODE REVIEW

**Comment by jeremydw** [comment]
Location will be in every sheet, but translator comments will only be on sheets where the developer has left comments for translators. Given this, should Comments be the last column?

**Comment by stevenle** [comment]
Thanks for making the change. I'll leave it up to @jeremydw to decide whether this is the right user behavior, but for what it's worth, I'd also be happy to have the translator comments appended directly to the "Location" column in the same way the po files have it.

Also - just checking, did you verify backwards-compatibility for existing sheets? From a quick skim of the code, I can't tell if columns are updated using a key-value mapping or if it's done by column index, if the latter, updating existing sheets might insert the translator comments into the wrong column.

**Comment by Zoramite** [comment]
@jeremydw My thoughts for having it be in third column instead of forth, is that if there are comments, then they are more important to the translators (who the sheet is made for) than the file that it is in.

@stevenle I think it would be better to be a separate column so that it doesn't confuse translators having the source information there as well. I think the translators would care more about the comment than the source file. And yes, it works in a backwards compatible way. :)

**Comment by jeremydw** [comment]
The comments are indeed important, but something that happens really frequently is users need to find + audit all strings used on a particular page, so it turns out the location information is really important. For example, a translator asks me "how do I find the translations corresponding to the <A> page?" and I say "search for "<A>" and then filter the view by cells that contain "<A>.yaml".

This flow is important for users - especially when they need to update just a handful of strings within a file that has dozens of pages and hundreds of strings.

**Comment by Zoramite** [comment]
Yeah, I think being able to see the source is still important, I thought that seeing the comments would be more helpful for normal translations. Having it be one column over wouldn't prevent the same filtering that they do now.

How about we add in a filter view that would allow them to filter down by the page? I would need to look into how to use it easily, but it might be a better way for finding translations by source?

**Comment by Zoramite** [comment]
I've created #423 to explore using a filter view to be able to do the filtering by page in a way that doesn't affect everyone using the doc.

**Pull request merged**
