### PR TITLE
Ignoring the node modules from the server filewatcher.

### PR DESCRIPTION
**Pull request by Zoramite**
Reduces the amount of watched files by a  *lot*.

### CODE REVIEW

**Comment by stevenle** [comment]
what files are tracked by the file watcher? wondering if we should add more items to that list.

**Comment by Zoramite** [comment]
Currently *all* files are watched by the watcher... are there others that we should add?

**Comment by stevenle** [comment]
i dunno how it's used in general, but maybe the modules that are creating the file watcher objects should send over a list of includes to watch. watching an entire project dir seems like a waste of resources if the only real directory you need to watch is `/content/`, for example.

**Comment by stevenle** [comment]
anyway, i think this change is probably good to go and sometime in the future you can maybe consider refactoring this module a bit so that there's more structure/transparency about which modules are watching which files. 

only other file that might be worth adding to the ignore right now is `/build/`.

**Pull request merged**
