### PR TITLE
Add Java to Docker image for use with Soy/Closure Templates extension

### PR DESCRIPTION
**Pull request by jeremydw**
Need to test this prior to merging to ensure there are no install prompts.

### CODE REVIEW

**Comment by stevenle** [comment]
I don't think this is a good idea. You can always create another docker image that inherits from the base grow image and install all of the extra dependencies that way. I don't think base grow necessarily needs to support Java since that's a lot of extra overhead.

**Comment by jeremydw** [comment]
Fair point – let's create a new image so projects that require Java can use it. What's the right convention here – `Dockerfile.java`? And, do we need to set up something else in Docker Hub to make this work?

**Comment by stevenle** [comment]
Do you need it as part of the core grow project? I feel like this is easy enough to do directly within the project folder that requires it instead of publishing to a public image.

But if you need a convention, you can maybe use the one that google cloud sdk uses:
https://github.com/GoogleCloudPlatform/cloud-sdk-docker

From their docs:

```
google/cloud-sdk:latest, google/cloud-sdk:VERSION: (large image with additional components pre-installed, Debian-based)

google/cloud-sdk:slim, google/cloud-sdk:VERSION-slim: (smaller image with no components pre-installed, Debian-based)

google/cloud-sdk:alpine, google/cloud-sdk:VERSION-alpine: (smallest image with no additional components installed, Alpine-based)
```

**Comment by jeremydw** [comment]
Abandoning this in favor of a project-local `Dockerfile` built with Google Cloud Build. If we have >1 project or a Grow extension requiring Java we can provide the `Dockerfile` and build instructions there.

**Pull request closed without merging**
