### PR TITLE
Manifest generation

### PR DESCRIPTION
**Pull request by chargrizzle**
Command to generate a manifest using list_statics, this is useful if you have a build pipeline that needs access to the static paths.

### CODE REVIEW

**Comment by jeremydw** [comment]
Thanks for the PR! Wondering... should this be a flag to the existing command, `grow routes`? `grow routes` shows all routes that are built by the site; rendered routes and static routes included. 

I wonder if we should add an `output_style` flag and a `type` flag (maybe named something different?) to support the functionality in the existing command?

**Comment by chargrizzle** [comment]
Sure! I'll add it to the existing command and we can get everything to dump as JSON

**Comment by jeremydw** [comment]
Awesome. `output_style=json` seems like it would make a lot of sense to me.

**Comment by chargrizzle** [comment]
Do you think it makes sense to just use stdout for this? The user could just pipe into a file if needed.

**Comment by jeremydw** [comment]
Yes; the `click` command line utility we're using supports a way to do this. It should be able to detect if the user is piping something to stdout and do the right thing. If the user isn't piping anything then it should display in a pager.

**Comment by jeremydw** [comment]
Notes:

http://click.pocoo.org/5/utils/#printing-to-stdout
http://click.pocoo.org/5/utils/#pager-support

**Comment by Zoramite** [comment]
To be consistent with how much we use yaml files, maybe have the default output be yaml and allow the `output_format=json` flag to output it as json?

And I like the idea of just piping the output to a file instead of specifying an output file as an argument.

**Comment by Zoramite** [comment]
@jeremydw  for separating out the static from the normal routes, what about doing a `filter=static` flag? Or would `type=static` be better?

**Comment by chargrizzle** [comment]
Do we want to expand all the routes here? 

For example the current route output is something like:
```
<Static(format='/source/images/{filename}')>
  /static/images/1.png
  /static/images/2.png
  /static/images/3.png
```
Would expected behaviour output individual maps?
```
{
 "/source/images/1.png":" /static/images/1.png",
 "/source/images/2.png":" /static/images/2.png",
 "/source/images/3.png":" /static/images/3.png"
}
```
or combined?
```
{
"/source/images/{filename}": ["/static/images/1.png", "/static/images/2.png", "/static/images/3.png"]
}
```
in which case would the full class repr still be the key? 
```
"<Static(format='/source/images/{filename}')>" or "/source/images/{filename}"?
```

Also for routes would it make more sense to use the doc as the key or the view? Maybe something that needs to be added as an option?

**Comment by Zoramite** [comment]
```json
{
"/source/images/{filename}": ["/static/images/1.png", "/static/images/2.png", "/static/images/3.png"]
}
```

Would be the better format for structuring since it adds the value of understanding which route is generating the filenames. And there is no need to use the entire `repr` for the key, just the format from the route should be enough.

**Comment by Zoramite** [comment]
I'm going to remove this for now. We now have the `routescache.json` file that contains all of the routing information from a build. So we can use that as a form of a manifest that can be parsed and used in a pipeline.

**Pull request closed without merging**
